### ISSUE TITLE
مشکلات هنگام نصب کتابخانه ها

### ISSUE THREAD

**Issue by Ho3EiNT79** [amirzenoozi/nsfw-classification#5]
باسلام خسته نباشید 
من هنگام نصب کتابخانه ها ابتدا به خطای 
`Double requirement given: async-timeout==4.0.3`
بعد از آن برای دوکتابخانه هم این خطارو میده که دستی نصبشون میکنم

سپس ارور 
`Could not find a version that satisfies the requirement Brlapi==0.8.5`
و برای چند کتابخانه دیگر با این خطا مواجه میشم که عبارتند از:
[lensfun, libfdt, louis, netsnmp-python==1.0a1, validate==5.0.8, validate-pyproject==0.13.post1.dev0+gb752273.d20230520, ]

سپس با خطا  `No matching distribution found for ipython==8.14.0` مواجه شدم که نسخه 8.13.0 رو نصب کردم
خطای `Could not find a version that satisfies the requirement pwquality==1.4.5`
یک سری از کتابخانه چند نسخه قدیمی نصب کردم 
یک سری هم شات گرفتم پیوست میکنم
![Annotation 2023-09-17 153201](https://github.com/amirzenoozi/nsfw-classification/assets/114897240/6c3f5cfd-c2a2-4f5b-a11a-41fe2233059e)
![Annotation 2023-09-17 145311](https://github.com/amirzenoozi/nsfw-classification/assets/114897240/6cc93c34-0191-46ae-8490-6f6ddfeb78e8)
![Annotation 2023-09-17 151348](https://github.com/amirzenoozi/nsfw-classification/assets/114897240/34d07c4d-08bf-49e2-a0fe-4d6b1ca3c86a)
![Annotation 2023-09-17 151949](https://github.com/amirzenoozi/nsfw-classification/assets/114897240/682d758a-d336-4fd5-b6cd-f3c0e65c1292)

**Comment by amirzenoozi** [comment]
این فایل براساس پایتون ورژن 3.8 تولید شده و ممکنه یه سری وابستگی به این نسخه از پایتون داشته باشه. 
اما در کل این فایل چیز عجیبی نیست و پکیج‌هارو به صورت جداگانه هم میتونید خودتون نصب کنید و پکیج‌های نصب شده هم پکیج‌ها معمول و کاملا رایجی هستن.
