### ISSUE TITLE
Can you make a little tutorial?

### ISSUE THREAD

**Issue by masterofobzene** [amirzenoozi/nsfw-classification#6]
I'm seeing the readme is upside down, I mean you first have to make the frames, then catalog. This, in the readme, is first catalog and then make frames; resulting in the first confusion.

The second confusion, is that you give this command:
`python main.py --dir PATH_TO_YOUR_DIR --model MODEL_FILE --jsob FOLDER_NAME`

Problem is, I don't know what "FOLDER_NAME" is supposed to be. I understand that "PATH_TO_YOUR_DIR" is where the frames of the video are, but what is "FOLDER_NAME"?

Can you clarify?

**Comment by masterofobzene** [comment]
also just realized that there is a typo on your command:
python main.py --dir PATH_TO_YOUR_DIR --model MODEL_FILE __--jsob__ FOLDER_NAME

should be --json

**Comment by masterofobzene** [comment]
OK, managed to make it work.
You probably should mention how this script works; it creates a json file with results, that is the "FOLDER_NAME" -> "Where you want the json file with results to be created".

I will have to play a lot with it to integrate it into automation.

**Comment by amirzenoozi** [comment]
Hi @masterofobzene 
.
sorry for my delay
If you update the `README.md` file or add a new `README.md` file in folders/subfolders. I will merge it and we will be sure that no one has your issue again.
